// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	config "github.com/jonjam/stock-checker/config"
	mock "github.com/stretchr/testify/mock"
)

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// GetLogConfig provides a mock function with given fields:
func (_m *Config) GetLogConfig() config.LogConfig {
	ret := _m.Called()

	var r0 config.LogConfig
	if rf, ok := ret.Get(0).(func() config.LogConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.LogConfig)
	}

	return r0
}

// GetNotifierConfig provides a mock function with given fields:
func (_m *Config) GetNotifierConfig() config.NotifierConfig {
	ret := _m.Called()

	var r0 config.NotifierConfig
	if rf, ok := ret.Get(0).(func() config.NotifierConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.NotifierConfig)
	}

	return r0
}

// GetRodConfig provides a mock function with given fields:
func (_m *Config) GetRodConfig() config.RodConfig {
	ret := _m.Called()

	var r0 config.RodConfig
	if rf, ok := ret.Get(0).(func() config.RodConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.RodConfig)
	}

	return r0
}

// GetSchedulerConfig provides a mock function with given fields:
func (_m *Config) GetSchedulerConfig() config.SchedulerConfig {
	ret := _m.Called()

	var r0 config.SchedulerConfig
	if rf, ok := ret.Get(0).(func() config.SchedulerConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.SchedulerConfig)
	}

	return r0
}

// GetTwilioConfig provides a mock function with given fields:
func (_m *Config) GetTwilioConfig() config.TwilioConfig {
	ret := _m.Called()

	var r0 config.TwilioConfig
	if rf, ok := ret.Get(0).(func() config.TwilioConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.TwilioConfig)
	}

	return r0
}
