# https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/
name: stock-checker-app
region: fra
workers:
- name: bg-worker-stock-checker
  github:
    branch: main
    deploy_on_push: true
    repo: JonJam/stock-checker
  dockerfile_path: Dockerfile

  # TODO Env vars ?
    # TODO Why doesn't run on Digital ocean
