version: "3.9"

services:
  app:
    build:
      context: ./..
      target: dev-runner 
    security_opt:
      - seccomp:unconfined
    container_name: stock-checker-$USER

    ports:
      - "40000:40000" #DEBUG

    # environment:
    #   - SC_
      # TODO Enable rod.trace in docker-compose