version: "3.9"

services:
  app:
    build:
      context: ./..
      target: dev-runner 
    # Enabling security_opt as advised here: https://github.com/golang/vscode-go/blob/master/docs/debugging.md#linuxdocker
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    container_name: stock-checker-$USER

    ports:
      - "40000:40000" # DEBUG

    # environment:
    #   - SC_
      # TODO Enable rod.trace in docker-compose