// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SmsClient is an autogenerated mock type for the SmsClient type
type SmsClient struct {
	mock.Mock
}

// send provides a mock function with given fields: body
func (_m *SmsClient) send(body string) error {
	ret := _m.Called(body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
